In [5]:
import numpy as np
ar_zero = np.zeros (4)
ar_zero1 = np.zeros((3,4))
print(ar_zero)
print()
print(ar_zero1)

[0. 0. 0. 0.]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [8]:
ar_empty = np.empty(3)
print(ar_empty)    

[ 0.00000000e+000  9.49920233e-312 -0.00000000e+000]


In [9]:
ar_rn= np.arange(7)
print(ar_rn)


[0 1 2 3 4 5 6]


In [14]:
arr_dia = np.eye(3)
print(arr_dia)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


linespace example in next code

In [17]:
arr_lin= np.linspace(0,20,num=5)
print(arr_lin)

[ 0.  5. 10. 15. 20.]


In [18]:
import numpy as np
var= np.random.rand(4)
print(var)

[0.38063664 0.54097176 0.75002018 0.28874994]


In [19]:
var1=np.random.rand(2,7)
print(var1)

[[0.0126467  0.11074157 0.41869893 0.21726487 0.36822069 0.83081718
  0.14233989]
 [0.48535339 0.30698545 0.33027947 0.46818608 0.70303881 0.21916068
  0.55099255]]


DATA TYPES IN NUMPY ARRAY

In [3]:
import numpy as np
var=np.array([1,2,3,4,5])
print("data type" , var.dtype) 

data type int64


In [4]:
x=np.array([1,2,3,4])
new1=x.astype(float)
print(x)
print(new1) 

[1 2 3 4]
[1. 2. 3. 4.]


ARITHMETIC OPERATION

In [5]:
var1=np.array([1,2,3,4])
var2=np.array([3,5,4,3])
varradd=np.add(var1,var2)
print(varradd)

[4 7 7 7]


In [2]:
import numpy as np
var=np.array([1,2,3,4])

print(np.max(var))
print(np.min(var))


4
1


SHAPE

In [4]:
import numpy as np
var = np.array([[1,2],[1,2]])
print(var)
print()
print(var.shape)

[[1 2]
 [1 2]]

(2, 2)


RESHAPE

In [10]:
var2=np.array([1,2,3,4,5,6,7,8,9,10,11,12])


x1= var2.reshape(2,3,2)
print(x1)
print(x1.ndim)

one=x1.reshape(-1)
print(one)
print(one.ndim)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
3
[ 1  2  3  4  5  6  7  8  9 10 11 12]
1


BROADCASTING - to add 2 arrays

In [12]:
import numpy as np
var=np.array([[1],[2]])
print(var.shape)

y=np.array([[1,2,3,],[1,2,3]])
print(y.shape)

print(var+y)

(2, 1)
(2, 3)
[[2 3 4]
 [3 4 5]]


INDEXING 


In [ ]:
#1d array
import numpy as np
var=np.array([9,7,6,5])
print(var[1])
print(var[-2])

7
6


In [16]:
#2d array
var1=np.array([[1,2,3],[4,5,6]])
print(var1)
print(var1.ndim)
print()

print(var1[0,1])

[[1 2 3]
 [4 5 6]]
2

2


In [18]:
#3d array
x=np.array([[[1,2],[3,4]]])
print(x)
print(x.ndim)

print(x[0,1,1])


[[[1 2]
  [3 4]]]
3
4


SLICING

In [22]:
y=np.array([1,2,3,4,5])
print(y.ndim)
print(y)
y[1:4]

1
[1 2 3 4 5]


array([2, 3, 4])