In [5]:
import numpy as np
ar_zero = np.zeros (4)
ar_zero1 = np.zeros((3,4))
print(ar_zero)
print()
print(ar_zero1)

[0. 0. 0. 0.]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [8]:
ar_empty = np.empty(3)
print(ar_empty)    

[ 0.00000000e+000  9.49920233e-312 -0.00000000e+000]


In [9]:
ar_rn= np.arange(7)
print(ar_rn)


[0 1 2 3 4 5 6]


In [14]:
arr_dia = np.eye(3)
print(arr_dia)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


linespace example in next code

In [17]:
arr_lin= np.linspace(0,20,num=5)
print(arr_lin)

[ 0.  5. 10. 15. 20.]


In [18]:
import numpy as np
var= np.random.rand(4)
print(var)

[0.38063664 0.54097176 0.75002018 0.28874994]


In [19]:
var1=np.random.rand(2,7)
print(var1)

[[0.0126467  0.11074157 0.41869893 0.21726487 0.36822069 0.83081718
  0.14233989]
 [0.48535339 0.30698545 0.33027947 0.46818608 0.70303881 0.21916068
  0.55099255]]
